accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login,name='login'),
    path('register/', views.register, name='register'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('logout/',views.logout, name='logout'),
    path('profile_edit/<user_id>/',views.profile_edit, name='profile_edit'),
    path('profile/<user_id>/',views.profile,name='profile'),
]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('',views.top_page_board,name='top_page_board'),
    path('good_board/',views.good_board,name='good_board'),
    path('store_board/',views.store_board,name='store_board'),
    path('search_board/',views.search_board,name='search_board'),
    path('post_board/',views.post_board,name='post_board'),
    path('evaluation/',views.evaluation,name='evaluation'),
    path('reply_comment/',views.reply_comment,name='reply_comment'),
    path('confirm_view_board/<board_id>/',views.confirm_view_board,name='confirm_view_board'),
    path('board_information/<board_id>/',views.board_information,name='board_information'),
    path('<board_id>/',views.board,name='board'),
]

discover/urls.py
from django.urls import path
from . import views

app_name = 'discover'

urlpatterns = [
    path('friend/',views.discover_friend,name='discover_friend'),
    path('room/',views.discover_room,name='discover_room'),
    path('change_relation_friend/',views.change_relation_friend,name='change_relation_friend'),
    path('change_relation_room/',views.change_relation_room,name='change_relation_room'),
    path('search_friend/',views.search_friend,name='search_friend'),
    path('search_room/',views.search_room,name='search_room'),
]

friend/urls.py
from django.urls import path
from . import views

app_name = 'friend'

urlpatterns = [
    # path('get_friend_timetable/',views.get_friend_timetable,name='get_friend_timetable'),
    path('',views.friend_home,name='friend_home'),
    path('<friend_id>/',views.friend_profile,name='friend_profile'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.about_mi_board,name='about_mi_board'),
    path('ranking/',views.ranking,name='ranking'),
    path('terms_of_use/',views.terms_of_use,name='terms_of_use'),
    path('privacy_policy/',views.privacy_policy,name='privacy_policy'),
]

mypage/urls.py
from django.urls import path
from . import views

app_name = 'mypage'

urlpatterns = [
    path('set_room/',views.set_room,name='set_room'),
    path('search_set_room/',views.search_set_room,name='search_set_room'),
    path('get_timetable/',views.get_timetable,name='get_timetable'),
    path('add_room_timetable/<room_id>/',views.add_room_timetable,name='add_room_timetable'),
    path('remove_seted_room/',views.remove_seted_room,name='remove_seted_room'),
    path('<user_id>/',views.mypage,name='mypage'),
]

room/urls.py
from django.urls import path
from . import views

app_name = 'room'

urlpatterns = [
    path('',views.room_home,name='room_home'),
    path('create_room/',views.create_room,name='create_room'),
    path('get_message/<room_id>/',views.get_message,name='get_message'),
    path('edit_room/',views.edit_room,name='edit_room'),
    path('<uuid:room_id>/',views.room,name='room'),
]

settings/urls.py
from django.urls import path
from . import views

app_name = 'settings'

urlpatterns = [
    path('home/',views.settings_home,name='settings_home'),
    path('room/',views.settings_room,name='settings_room'),
    path('send_report/',views.send_report,name='send_report'),
    path('list_report/',views.list_report,name='list_report'),
    path('list_user_info/',views.list_user_info,name='list_user_info'),
    path('points_history/',views.points_history,name='points_history'),
    path('stoppo_settings/',views.stoppo_settings,name='stoppo_settings'),
    path('change_room_name/<room_id>',views.change_room_name,name='change_room_name'),
]

board/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Boards,BoardComment,PurchaseHistory,GoodBoard,StoreBoard
from django.http import HttpResponse,JsonResponse
from recommend_system.models import BrowsingHistory,SearchHistory
from recommend_system import views as recommend_system
from accounts.models import Users,PointsHistory
from django.db.models import Q
from room.models import RoomJoining,Rooms
from django.utils import timezone
from notification.models import Notification
# Create your views here.

class TopPageBoardView(LoginRequiredMixin,View):
    def get(self,request,*args,**kwargs):

        try:
            board_list_from_recommend_system = recommend_system.create_recommend_board_list(request)
            selected_board_list = Boards.objects.filter(board_id__in = board_list_from_recommend_system)
            recommend_board_list = []
            for index,_ in enumerate(board_list_from_recommend_system):
                for _1 in selected_board_list:
                    if board_list_from_recommend_system[index] == _1.board_id:
                        recommend_board_list.append(_1)


        except:
            recommend_board_list = Boards.objects.all().order_by('created_at').reverse()[:10]

        latest_board_list = Boards.objects.exclude(posted_by_id=request.user.user_id)[:20]

        board_list = Boards.objects.all().values('board_id','category','title','content','tags','bet_points','attached_image','display_name','related_room_id')

        latest_search_word = set(SearchHistory.objects.values_list('search_word',flat=True).reverse()[0:8])

        related_room_list = RoomJoining.objects.filter(user_id = request.user.user_id)


        context = {
            'board_list':board_list,
            'recommend_board_list':recommend_board_list,
            'latest_board_list':latest_board_list,
            'latest_search_word':latest_search_word,
            'related_room_list':related_room_list,
        }

        return render(request,'top-page_board.html',context)

    def post(self,request,*args,**kwargs):

        if request.GET:
            search_terms = request.GET

        else:
            search_terms = request.POST
            search_history = SearchHistory(search_user_id=request.user.user_id,search_word=search_terms['search_word'])
            search_history.save()


        if search_terms['filtering_department'] == '全て':
            search_result = Boards.objects.filter(Q(title__istartswith=search_terms['search_word'])|Q(tags__istartswith=search_terms['search_word'])).order_by('created_at').reverse()
            if search_terms['selection_style_board'] == '全て':
                search_result = Boards.objects.filter(Q(title__istartswith=search_terms['search_word'])|Q(tags__istartswith=search_terms['search_word'])).order_by('created_at').reverse()

            else:
                search_result = Boards.objects.filter(Q(title__istartswith=search_terms['search_word'])|Q(tags__istartswith=search_terms['search_word']),category=search_terms['selection_style_board']).order_by('created_at').reverse()


        else:
            search_result = Boards.objects.filter(Q(title__istartswith=search_terms['search_word'])|Q(tags__istartswith=search_terms['search_word']),related_department=search_terms['filtering_department']).order_by('created_at').reverse()

            if search_terms['selection_style_board'] == '全て':
                search_result = Boards.objects.filter(Q(title__istartswith=search_terms['search_word'])|Q(tags__istartswith=search_terms['search_word']),related_department=search_terms['filtering_department']).order_by('created_at').reverse()

            else:
                search_result = Boards.objects.filter(Q(title__istartswith=search_terms['search_word'])|Q(tags__istartswith=search_terms['search_word']),related_department=search_terms['filtering_department'],category=search_terms['selection_style_board']).order_by('created_at').reverse()

        try:
            base_user = request.user.user_id
            random_extracting_user = Users.objects.filter(university = request.user.university).exclude(user_id=request.user.user_id).order_by('?')[:30].values_list('user_id',flat=True)
            recommend_board_list = recommend_system.get_recommend_board_main(base_user,random_extracting_user)

        except:
            recommend_board_list = Boards.objects.filter(university=request.user.university)[0:8]

        context = {
            'search_result_board_list':search_result,
            'recommend_board_list':recommend_board_list,
        }

        return render(request,'board_search_result.html',context)

top_page_board = TopPageBoardView.as_view()

@login_required
def preview_board_image(request):
    return JsonResponse()


class BoardView(LoginRequiredMixin,View):
    def get(self,request,*args,**kwargs):
        add_history = BrowsingHistory(user_id = request.user.user_id,board_id = self.kwargs['board_id'])
        add_history.save()


        try:
            base_user = request.user.user_id
            random_extracting_user = Users.objects.filter(university = request.user.university).exclude(user_id=request.user.user_id).order_by('?')[:30].values_list('user_id',flat=True)
            recommend_board_list = recommend_system.get_recommend_board_sub(base_user,random_extracting_user)

        except:
            recommend_board_list = Boards.objects.filter(university=request.user.university)[0:8]

        board_content = Boards.objects.get(board_id = self.kwargs['board_id'])
        board_post_user_data = Users.objects.get(user_id = board_content.posted_by_id)
        board_comment_list = BoardComment.objects.filter(comment_board_id = self.kwargs['board_id']).values().order_by('created_at').reverse()

        board_views = BrowsingHistory.objects.filter(board_id = self.kwargs['board_id']).count()

        good_board_id_list = GoodBoard.objects.filter(good_user_id = request.user.user_id).values_list('board_id',flat=True)
        store_board_id_list = StoreBoard.objects.filter(store_user_id = request.user.user_id).values_list('board_id',flat=True)

        context = {
            'board_content':board_content,
            'board_post_user_data':board_post_user_data,
            'recommend_board_list':recommend_board_list,
            'board_comment_list':list(board_comment_list),
            'board_views':board_views,
            'good_board_id_list':good_board_id_list,
            'store_board_id_list':store_board_id_list,
        }

        return render(request,'board.html',context)

    def post(self,request,*args,**kwargs):
        return HttpResponse('')

def search_board(requset):
    return HttpRespons('')

board = BoardView.as_view()


@login_required
def post_board(request):
    if request.method == 'POST':
        new_board_data = request.POST

        if int(new_board_data['bet_points']) < 0:
            return redirect('board:top_page_board')

        if(int(Users.objects.get(user_id=request.user.user_id).points) < int(new_board_data['bet_points']) and (new_board_data['category'] == '質問')):
            return redirect('board:top_page_board')

        elif int(Users.objects.get(user_id=request.user.user_id).points) > int(new_board_data['bet_points']) and (new_board_data['category'] == '質問'):
            consume_points_user = Users.objects.get(user_id = request.user.user_id)
            consume_points_user.points = int(consume_points_user.points) - int(new_board_data['bet_points'])
            consume_points_user.save()

        if int(new_board_data['bet_points']) != 0 and (new_board_data['category'] == '質問'):
            record_consume_points = PointsHistory(is_consumption=True,consumed_user_id=request.user.user_id,consumed_points=int(new_board_data['bet_points']),detail='ポイントを使って質問しました')
            record_consume_points.save()

        new_board_data_image_file = request.FILES

        try:
            if new_board_data_image_file['attached_image']:
                pass
        except:
            new_board_data_image_file['attached_image'] = ''

        try:
            if new_board_data_image_file['attached_file']:
                pass
        except:
            new_board_data_image_file['attached_file'] = ''


        create_board_data = Boards(category = new_board_data['category'],
                                    title = new_board_data['title'],
                                    content = new_board_data['content'],
                                    tags = new_board_data['tags'],
                                    related_department = new_board_data['related_department'],
                                    related_room_id = new_board_data['related_room'],
                                    bet_points = new_board_data['bet_points'],
                                    display_name = new_board_data['select_post_user'],
                                    posted_by_id = request.user.user_id,
                                    attached_image = new_board_data_image_file['attached_image'],
                                    attached_file = new_board_data_image_file['attached_file'],
                                    university = request.user.university)

        create_board_data.save()

        if new_board_data['related_room']:
            update_room = Rooms.objects.get(room_id = new_board_data['related_room'])
            update_room.last_update = timezone.now()
            update_room.save()

            display_name = Rooms.objects.get(room_id = new_board_data['related_room'])
            joining_room_id_list = RoomJoining.objects.filter(room_id = new_board_data['related_room']).exclude(user_id = request.user.user_id).values_list('user_id',flat=True)
            notification_list = []
            for notification in list(joining_room_id_list):

room/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Rooms,RoomJoining,RoomMessage
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,JsonResponse
from django.db import connection
from accounts.models import Users
from board.models import Boards
from django.utils import timezone
# Create your views here.

@login_required
def room_home(request):

    room_list = RoomJoining.objects.filter(user_id = request.user.user_id)

    context = {
        'room_list':room_list,
    }
    return render(request,'room_home.html',context)

class RoomView(LoginRequiredMixin,View):
    def get(self,request,*args,**kwargs):
        room_data = Rooms.objects.get(room_id = self.kwargs['room_id'])
        room_joining = RoomJoining.objects.filter(user_id = request.user.user_id).values_list('room_id',flat=True)

        room_joining_user_list = RoomJoining.objects.filter(room_id = self.kwargs['room_id']).exclude(user_id = request.user.user_id)

        related_board_list = Boards.objects.filter(related_room_id = self.kwargs['room_id']).order_by('created_at').reverse()

        try:
            update_last_access = RoomJoining.objects.get(room_id = self.kwargs['room_id'],user_id = request.user.user_id)
            update_last_access.last_access = timezone.now()
            update_last_access.save()

        except:
            pass


        context = {
            'room_data':room_data,
            'room_joining':list(room_joining),
            'room_joining_user_list':list(room_joining_user_list),
            'num_joining_user':len(room_joining_user_list),
            'related_board_list':related_board_list,
        }

        return render(request,'room.html',context)

    def post(self,request,*args,**kwargs):
        return HttpResponse('here')

room = RoomView.as_view()

@login_required
def create_room(request):
    try:
        if request.method == 'POST':
            new_room_data = request.POST
            new_room_data_image = request.FILES

            try:
                if new_room_data_image['room_image']:
                    pass

            except:
                new_room_data_image['room_image'] = ''

            create_room_data = Rooms(room_name=new_room_data['room_name'],
                                    representative_person_name=new_room_data['representative_person_name'],
                                        category=new_room_data['category'],
                                        work_time=new_room_data['work_time'],
                                        subject_to=new_room_data['subject_to'],
                                        room_image=new_room_data_image['room_image'],
                                        week_at=new_room_data['week_at'],
                                        university=request.user.university)
            create_room_data.save()

    except:
        return redirect('room:room_home')

    return redirect('room:room_home')

class EditRoomView(LoginRequiredMixin,CreateView):
    model = Rooms
    fields = ['room_name']

edit_room = EditRoomView.as_view()

@login_required
def get_message(request,room_id):
    if request.method == 'GET':
        room_id = request.GET.get('room_id')
        message_list = RoomMessage.objects.filter(room_id = room_id).values('message','send_user_id')
        return JsonResponse({'message_list':list(message_list)})

templates/discover_friend.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<html lang='ja'>
<head>
  <meta charset='utf-8'>
  {% block title %}<title> DiscoverFriend | Mi-Board</title>{% endblock %}
  {% block head %}
  <link rel='stylesheet' type='text/css' href="{% static 'css/discover_friend.css' %}" />
  <script type="text/javascript" src="{% static 'js/discover_friend.js' %}"></script>
  {% endblock %}
</head>

<body>
  {% block content %}
  <form id='search_friend_form' method="" action="" onsubmit="return false">
      <a href='{% url "discover:discover_room" %}' class='change_search_option_link'><img src="{% static 'image/room.svg' %}" class='change_search_option'></a>
      <input type='search' name='search' placeholder="友達を探す" id='search_friend_input'>
      <p style='font-size:0.6vw; font-weight:bold; margin:0 0.4vw; opacity:0.8;'>条件</p>
      <select form='search_friend_form' class='narrowed_down_menu'>
        <option value='user_name'>名前</option>
        <option value='university'>大学</option>
        <option value='department'>学部</option>
        <option value='circle'>サークル</option>
        <option value='part_time_job'>バイト先</option>
        <option value='hometown'>出身</option>
        <option value='high_school'>出身高校</option>
      </select>
  </form>

  <p class='recommend_friend' style='margin: 1vh 0 1vh 0; opacity: 0.7; font-weight: bold;'>おすすめの友達</p>

  <ul class='friend_card_container'>
  {% for account in accounts_list %}
  <li class='friend_card' role='article'>
    <div class='friend_img_detail'>
    <a href='{% url "friend:friend_profile" account.user_id %}' style='display:flex; align-items:center;'>
      {% if account.user_icon_image %}
      <img src='/media/{{ account.user_icon_image }}' class='friend_icon'>
      {% else %}
      <img src='/static/image/user.svg' class='friend_icon'>
      {% endif %}
    </a>

    <div class='friend_detail'>
      <p class='user_attribution'>{{ account.university }}|{{ account.department }}</p>
      <a href='{% url "friend:friend_profile" account.user_id %}' id='friend_name'>{{ account.last_name }}{{ account.first_name }}</a>
    </div>
  </div>

    {% if account.user_id in follows %}
    <button class='btn-change-relation {{account.user_id}}' value='{{ account.user_id }}' id='unfollow' name='unfollow'>フォロー解除</button>
    {% else %}
    <button class='btn-change-relation {{account.user_id}}' value='{{ account.user_id }}' id='follow' name='follow'>フォロー</button>
    {% endif %}

  </li>
  {% endfor %}
  </ul>


  {% endblock %}
</body>
</html>

templates/room.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
<!doctype html>
<html lang='ja'>
<head>
  <meta charset='utf-8'>
  {% block title %}<title>{{room_data.room_name}} | Room | Mi-Board</title>{% endblock %}
  {% block head %}
  <link rel='stylesheet' type='text/css' href="{% static 'css/room.css' %}" />
  <script type="text/javascript" src="{% static 'js/room.js' %}"></script>
  {% endblock %}
</head>

<body>
  {% block content %}

<div id='smartfon_room_detail'>
  {% if room_data.room_image %}
    <img src='/media/{{room_data.room_image}}'>
  {% else %}
    <img src='/static/image/room.svg'>
  {% endif %}
  <h1>{{room_data.room_name}}</h1>
  <ul>
    <li class='smartphone_room_detail'><p>{{ room_data.representative_person_name }}</p></li>
    <li class='smartphone_room_detail'><p>{{ room_data.week_at }}</p></li>
    <li class='smartphone_room_detail'><p>{{ room_data.work_time }}時間目</p></li>
    <li class='smartphone_room_detail'><p>{{ room_data.subject_to }}</p></li>
  </ul>
  {% if room_data.room_id in room_joining %}
  <button class="btn-change_relation {{ room_data.room_id }}" id='secession' value='{{ room_data.room_id }}' name='secession'>退出</button>
  {% else %}
  <button class="btn-change_relation {{ room_data.room_id }}" id='join' value='{{ room_data.room_id }}' name='join'>参加</button>
  {% endif %}
</div>

  <div class='room_info-room_chat'>
    <div class='room_info_container'>
      <div class='room_info'>
        {% if room_data.room_image %}
        <img src='/media/{{ room_data.room_image }}' class='room_icon'>
        {% else %}
        <img src='/static/image/room.svg' class='room_icon'>
        {% endif %}
        <h1 class='room_name'>{{ room_data.room_name }}</h1>

        <div class='btn-room_action'>
          {% if room_data.room_id in room_joining %}
          <button class="btn-change_relation {{ room_data.room_id }}" id='secession' value='{{ room_data.room_id }}' name='secession'>退出</button>
          {% else %}
          <button class="btn-change_relation {{ room_data.room_id }}" id='join' value='{{ room_data.room_id }}' name='join'>参加</button>
          {% endif %}
          <a href='#' class="btn-room_action_design" id='btn-copy-link'>リンクコピー</a>
          </div>

        <p class='room_description'>{{ room_data.representative_person_name }}</p>
        {% if room_data.week_at == 'その他' %}
        <p class='room_description'>任意</p>
        {% else %}
        <p class='room_description'>{{ room_data.week_at }}</p>
        {% endif %}
        {% if not room_data.work_time == 10 %}
        <p class='room_description'>{{ room_data.work_time }} 時間目</p>
        {% endif %}
        {% if room_data.subject_to == 'その他' %}
        <p class='room_description'>サークル</p>
        {% else %}
        <p class='room_description'>{{ room_data.subject_to }}</p>
        {% endif %}
      </div>

    </div>

  <div class='room_chat_container'>
    <div id='room_chat'>
    </div>

    <div class='send_message_container'>
      <input type='text' placeholder="メッセージを入力" id='send_message_input_room' maxlength='254'>
    </div>
  </div>

  </div>

  <div class='room_detail_container'>
    <ul class='room_joining_user_list_container'>
      <p class='guide_box'>{{num_joining_user}}人の参加ユーザー</p>
      {% for joining_user in room_joining_user_list %}
      <li class='joining_user_item'>
        <a href='{% url "friend:friend_profile" joining_user.user.user_id %}' class='joining_user_item_link'>
          {% if joining_user.user.user_icon_image %}
          <img class='joining_user_image' src='/media/{{joining_user.user.user_icon_image}}'>
          {% else %}
          <img class='joining_user_image' src='{% static "image/user.svg" %}'>
          {% endif %}
          <div class='joining_user_detail'>
            <p>{{joining_user.user.department}}{{joining_user.user.division}}</p>
            <h2>{{joining_user.user.last_name}} {{joining_user.user.first_name}}</h2>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>

    <ul id='related_board_box'>
      <p class='guide_box'>{{related_board_list|length}}件の関連投稿</p>
      {% for board in related_board_list %}
      <li class='related_board_card'>
        {% if board.category == '記事' %}
        <a href='{% url "board:board_information" board.board_id %}' class='related_board_link' style='width:100%; font-size:0.75vw;text-decoration:none;color:black; font-weight:bold;'><span style='font-size:0.6vw; font-weight:normal;'><span class='related_board_created_at'>{{board.created_at|date:'Y-m-d'}}</span> | [{{board.category}}|{{board.bet_points}}ポイント]</span> {{board.title}}</a>
        {% else %}
        <a href='/board/{{board.board_id}}/' class='related_board_link' style='width:100%; font-size:0.75vw;text-decoration:none;color:black; font-weight:bold;'><span style='font-size:0.6vw; font-weight:normal;'><span class='related_board_created_at'>{{board.created_at|date:'Y-m-d'}}</span> | [{{board.category}}|{{board.bet_points}}ポイント]</span> {{board.title}}</a>
        {% endif %}
      </li>
      {% endfor %}
    </ul>

  </div>


  <ul id='related_board_box_main'>

    <div id='post_board'>
      <p class='post_guide_message'>投稿する/ファイルをシェアする</p>
      <a href='javascript:void(0);' id='dummy_input_board'>| 投稿内容を入力</a>
    </div>
    {% if related_board_list %}
    <p class='related_board_guide_message'>これまでの投稿</p>
    {% endif %}
    {% for board in related_board_list %}
    <li class='related_board_item'>
        <div class='related_board_detail'>
          {% if board.display_name == 'anonymous' %}
          <img src='{% static "image/user.svg"%}' class='board_post_user_icon'><p class='board_post_username'>匿名さん</p>
          {% else %}
          <a href='{% url "friend:friend_profile" board.posted_by_id %}' class='related_board_user_link'><img src='/media/{{board.posted_by.user_icon_image}}'class='board_post_user_icon'><p class='board_post_username'>{{board.posted_by.last_name}}{{board.posted_by.first_name}}</p></a><p class='related_board_datetime related_board_created_at'>{{board.created_at|date:'Y-m-d'}}</p>
          {% endif %}
        </div>
        <div class='related_board_body'>
          {% if board.category == '記事' %}
          <a class='related_board_title related_board_article' href='{% url "board:board_information" board.board_id %}'>{{board.title}}</a>
          {% else %}
          <a class='related_board_title' href='{% url "board:board" board.board_id %}'>{{board.title}}</a>
          {% endif %}
          {% if board.category == '記事' %}
          <a class='related_board_content blur related_board_article_content' href='{% url "board:board_information" board.board_id %}'>この記事の内容はポイント消費で取得後に閲覧可能になります。</a>
          {% else %}
          <a class='related_board_content' href='#'>{{board.content}}</a>
          {% endif %}
        </div>
        {% if board.attached_image %}
        {% if board.category == '記事' %}
        <a href='{% url "board:board_information" board.board_id %}' class='related_board_image_link related_article_board_image_link'>
          <img src='{% static "image/board.svg"%}' style='width:20vw;' class='related_board_image related_board_article_image blur'>
        </a>
        {% else %}
        <a href='{% url "board:board" board.board_id %}' class='related_board_image_link'>
        <img src='/media/{{board.attached_image}}/' class='related_board_image'>
        </a>
        {% endif %}
        {% endif %}
        {% if board.attached_file %}
        {% if board.category == '質問' %}
        <a href='{% url "board:board" board.board_id %}' class='related_board_attached_file'>この投稿には添付ファイルがあります</a>
        {% else %}
        <a href='{% url "board:board_information" board.board_id %}' class='related_board_attached_file related_board_article_attached_file'>この投稿には添付ファイルがあります</a>
        {% endif %}
        {% endif %}
        <p class='related_board_category_points'>{{board.category}} | {{board.bet_points}}ポイント</p>
    </li>
    {% endfor %}
  </ul>



<div>
</div>

<div id='post_board_page_bg'>
  <form id='post_board_page' method='post' action='{% url "board:post_board" %}' enctype="multipart/form-data" name='post_board_input_form'>
    {% csrf_token %}
    <p>タイトル</p>
    <input type='text' name='title' placeholder='タイトル(120字以内)' id='input_title'>
    <p>本文</p>
    <textarea name='content' placeholder='内容(800字以内)' id='input_content' style='height:12vh;'></textarea>
    <p>タグ</p>
    <input type='text' name='tags' placeholder='例)課題　例)過去問' id='input_tags'>
    <p>設定コイン</p>
    <select name='bet_points' id='input_bet_points'>
        <option value='0'>0ポイント</option>
        <option value='3'>3ポイント</option>
        <option value='5'>5ポイント</option>
        <option value='10'>10ポイント</option>
        <option value='15'>15ポイント</option>
        <option value='30'>30ポイント</option>
    </select>
    <p>添付画像</p>
    <input type="file" name="attached_image" id='input_attached_image'>
    <p>添付ファイル</p>
    <input type="file" name="attached_file" id='input_attached_file'>
    <p>投稿タイプ</p>
    <select name='category' id='input_category'>
      <option value='質問'>質問</option>
      <option value='記事'>記事</option>
    </select>


    <p>投稿者名</p>
    <div class='select_post_user_container'>
    <input type='radio' name='select_post_user' id='input_anonymous' value='anonymous' class='radio_input'>
    <label for='input_anonymous' class='radio_label'>匿名</label>
    </div>

    <div class='select_post_user_container'>
    <input type='radio' name='select_post_user' id='input_real_name' value='real_name' class='radio_input' checked>
    <label for='input_real_name' class='radio_label'>実名</label>
    </div>

    <input type='hidden' name='related_department' value='{{ room_data.subject_to }}'>
    <input type='hidden' name='related_room' value='{{room_data.room_id}}'>
    <button type='submit' style='font-size: 0.7vw; font-weight:bold; margin: 0.3vh 0;'>投稿</button>
   </form>
</div>

<input type='hidden' value={{ room_data.room_id }} id='message_room_id'>
<input type='hidden' value={{ user.user_id}} id='message_user_id'>

<script>
  var date = '{% now "Y" %}-{% now "m" %}-{% now "d" %}'
  $('.related_board_created_at').each(function(){
    if($(this).html() == date){
      $(this).attr('style','color:red; font-weight:bold;')
    }
  })
</script>
  {% endblock %}
</body>
</html>

templates/settings_home.html
{% extends 'base.html' %}
{% load static %}
<!doctype html>
<html lang='ja'>
<head>
  <meta charset='utf-8'>
  {% block title %}<title> SettingsHome | Mi-Board</title>{% endblock %}
  {% block head %}
  <link rel='stylesheet' type='text/css' href="{% static 'css/discover_friend.css' %}" />
  {% endblock %}
</head>

<body>
  {% block content %}

  <h2>管理者ページ</h2>
  <a href='{% url "home:about_mi_board" %}'>Welcome Page</a>
  <a href='{% url "settings:settings_room" %}'>ルーム情報変更</a>
  <a href='{% url "settings:list_report" %}'>レポート確認</a>
  <a href='{% url "settings:list_user_info" %}'>ユーザー情報一覧</a>
  <a href='{% url "settings:stoppo_settings" %}'>STOPPO管理</a>
  <a href='{% url "home:privacy_policy" %}'>利用規約</a>
  <a href='{% url "home:terms_of_use" %}'>プライバシーポリシー</a>

  {% endblock %}
</body>
</html>